### ISSUE TITLE
Поддержка Votifer

### ISSUE THREAD

**Issue by BlackRandomCraft** [4haz2k/GSMS#2]
Добавьте поддержку Votifer

**Comment by 4haz2k** [comment]
Votifier старый плагин (дата последней выпущенной версии 2015 год). На замену ему есть плагин NuVotifier, но там не используется безопасное шифрование, да и к тому же в их GitHub профиле большое количество ошибок, на которые создатели плагина никак не реагируют. 

Мы подумаем над его добавлением в нашу систему, взвесим все за и против. Стоит учитывать, что помимо Minecraft, на нашем сайте используются и другие игры. Поэтому данный плагин не вписывается в концепцию интерфейса системы. 

Вместо него у нас используется более безопасная и универсальная система голосований, которая подходит под концепт интерфейса нашей системы - REST API (server-server). Более подробно вы можете прочитать об этом механизме на нашей странице WIKI https://github.com/4haz2k/mnsgame/wiki/%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0-%D0%B3%D0%BE%D0%BB%D0%BE%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82. Спасибо
